name: "Snowflake Terraform Demo Workflow for dev environment"

on:
  push:
    branches: [dev]
    paths:
      - 'modules/**'

jobs:
  snowflake-terraform-dev:
    name: "Snowflake-Dev"
    runs-on: ubuntu-latest
    environment: dev
    env:
      TF_VAR_env: "DEV"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
