name: "terraform_apply_dev"

on:
  workflow_run:
    workflows: [ terraform_plan_dev ]
    types: [completed]
    branches: [dev]
    paths:
      - 'terraform/**'

jobs:
  terraform-plan:
    name: "Terraform-Apply"
    
    strategy:
      matrix:
        folder: ['./terraform']
        
    runs-on: ubuntu-latest
    environment: dev
    env:
      TF_VAR_env: "DEV"
      TF_VAR_snowflake_account: "${{vars.SNOWFLAKE_ACCOUNT}}"
      TF_VAR_snowflake_region: "${{vars.SNOWFLAKE_REGION}}"
      TF_VAR_snowflake_username: "${{vars.SNOWFLAKE_USERNAME}}"
      TF_VAR_snowflake_private_key: "${{secrets.SNOWFLAKE_PRIVATE_KEY}}"
      TF_VAR_snowflake_role: "${{vars.SNOWFLAKE_ROLE}}"
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
